      MODULE MO_COMMOAU1
!==>COMMOAU1
      COMMON/HOPEICC/ENTMEL,TFREEZ,SICHEC,STEBOL,HTH00,HICCE,HICCP,CW
      COMMON/COMGRO/ALBI,ALBM,ALBW,ALBSN,ALBSNM,CONSN,RHOICE,H0,ARMIN,  &
     &   ARMAX,HMIN,RHOSNO,CC,RHOWAT,SICE,SICTHMIN,HSNTOICE,VAPL,SUBL,  &
     &   RHOSNWA,RHOICWA,RHOSNIC,ISNFLG
      COMMON/COMBUD/CLO,CLB,D1,D2W,D2I,D3,TMELT,TFREZ,CON,RHOAIR
!<==END COMMOAU1
      END MODULE MO_COMMOAU1
